### ISSUE TITLE
Update kube-prometheus-stack version to 31.0.0

### ISSUE THREAD

**Issue by bradmccoydev** [bradmccoydev/mentoring#190]
Update kube-prometheus-stack version to 31.0.0

This is to be updated in 2 repos first update bradmccoydev one then copy the "kube-prometheus-stack" folder to the ortelius kubernetes  repo under kube-infra/kustomize/test

https://github.com/bradmccoydev/argo-demo
https://github.com/ortelius/ortelius-kubernetes

Follow the contributing guide in the mentoring repo for the PR. PR's will not be accepted if you do not follow the guide. eg branch away from main, sign commits etc.

All you need to do is change the version number and nothing else. Line 4 and on the following path:
kube-infra/kustomize/test/kube-prometheus-stack/base/kustomization.yaml

change the version number to 31.0.0

Reference to Artifacthub: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

**Comment by hamidgholami** [comment]
Hi,
These are my PRs regarding to this task.

https://github.com/bradmccoydev/argo-demo/pull/4
https://github.com/ortelius/ortelius-kubernetes/pull/19
